Update verify_json.yml

diff --git a/.github/workflows/verify_json.yml b/.github/workflows/verify_json.yml
--- a/.github/workflows/verify_json.yml
+++ b/.github/workflows/verify_json.yml
@@ -30,8 +30,7 @@ jobs:
       - name: Verify eggd prefix in name
         if: always()
         run: |
-          name=$(jq -r '.name' <<< $DXAPP_JSON)
-          if [[ "$name" != eggd_* ]]; then echo "Missing eggd_ prefix from name"; exit 1; fi
+          if [[ $(jq -r '.name' <<< $DXAPP_JSON) != eggd_* ]]; then echo "Missing eggd_ prefix from name"; exit 1; fi
       
       - name: Verify eggd prefix in title
         if: always()
@@ -51,6 +50,7 @@ jobs:
       - name: Verify developers set to org-emee_1
         if: always()
         run: |
+          jq -r '.developers[]'
           if [[ $(jq -r '.developers[]' <<< $DXAPP_JSON) == 'org-emee_1' ]]; then echo "Developers not set to org-emee_1"; exit 1; fi
       
       - name: Verify authorizedUsers set to org-emee_1
